artusjs/core

- src/scanner/scan.ts
defaultExtensions may contain same element with options.extensions
> scnaner: 调试发现extensions出现重复

- src/index.ts
`artus/core` 入口缺少 `./decorator`, `./types` 和 `./constraints` 这三个文件的导出
正式 release 后会使用 `export` 限制只能从入口访问导出内容
> fix: export missing files

- src/application.ts
- src/configuration/index.ts
- src/framework/handler.ts
- src/loader/factory.ts
- src/plugin/base.ts
- src/plugin/common.ts
- src/plugin/factory.ts
- src/plugin/types.ts
- src/scanner/scan.ts
- src/scanner/types.ts
- src/types.ts
- test/framework.test.ts
- test/scanner.test.ts
* 启动器更改为 Env 无关（除了 config），移除了 Env 过滤 Manifest item 相关的逻辑
* 扫描器更改为 Env 有关，允许传入多个 Env 获取对应的多份 Manifest（格式参见 [RFC](https://github.com/artusjs/core/issues/49)）
* Plugin 的实现还原为之前的逻辑
close https://github.com/artusjs/core/issues/49
> refactor: scan files by env

- src/configuration/index.ts
- src/framework/handler.ts
- src/scanner/scan.ts
- src/scanner/types.ts
- test/framework.test.ts
- scan 方法 envs 统一到 ScannerOptions
- options.envs 不传场景下，扫描 configDir 获得有效的 env 列表
- 配置文件 env 抽象工具方法
- ConfigurationHandler 抽象 setConfigByFile 减少 plugin/framework 重复代码
> feat(scanner): 支持通过遍历 configDir 获得待扫描 env 列表

- src/index.ts
- src/scanner/scan.ts
- test/fixtures/app-koa-with-ts/src/config/plugin.d.ts
- test/scanner.test.ts
`tsc` 打包后会默认生成 `.d.ts` 声明文件，此时 Scanner 扫描 config 目录时对于 `plugin.ts` 等默认 Env 配置会错误扫描 `plugin.d.ts` 从而得到 Env `d`：
```js
{
default: {
items: [
[Object], [Object],
[Object], [Object],
[Object], [Object],
[Object]
]
},
d: {
items: [
[Object], [Object],
[Object], [Object],
[Object], [Object],
[Object], [Object],
[Object], [Object],
[Object], [Object],
[Object], [Object]
]
}
}
```
需要在 Scanner 中忽略 `.d.ts` 申明文件
> fix: should ignore d.ts

- src/application.ts
- src/loader/factory.ts
- src/loader/types.ts
- src/scanner/scan.ts
- test/fixtures/artus_application/src/index.ts
在 #81 的基础上，对 Manifest 增加了 `relative` 可选字段属性，如果为 true，则在启动期通过 `path.join` 应用根路径的形式启动，否则按照原有启动流程。
注意：此 feature 为在原有流程上的新增，不存在 `relative` 属性或者其为 `false` 时不会 break 原有启动和扫描流程。
close #79
> feat: support relative path

- src/application.ts
- src/configuration/decorator.ts
- src/configuration/index.ts
- src/constant.ts
- src/decorator.ts
- src/exception/error.ts
- src/index.ts
- src/lifecycle/index.ts
- src/loader/decorator.ts
- src/loader/factory.ts
- src/loader/impl/config.ts
- src/loader/impl/exception.ts
- src/loader/impl/framework_config.ts
- src/loader/impl/lifecycle.ts
- src/loader/impl/package.ts
- src/loader/impl/plugin_config.ts
- src/logger/base.ts
- src/logger/decorator.ts
- src/logger/level.ts
- src/plugin/types.ts
- src/scanner/scan.ts
- src/scanner/utils.ts
- src/trigger/decorator.ts
- src/trigger/index.ts
- test/config.test.ts
- test/fixtures/frameworks/bar/src/http.ts
- test/framework.test.ts
- 修正错误命名 `constraint` 英语水平太差害死人
- 导出量中移除 const enum，方便下游对常量做扩展
> fix: 常量表命名 & 移除 const enum

- src/plugin/base.ts
如果同时存在path和package来声明plugin，path优先级高
> feat: plugin decleare, path priority over package

- src/loader/impl/config.ts
- src/loader/impl/framework_config.ts
- src/loader/impl/plugin_config.ts
- src/plugin/base.ts
- src/plugin/impl.ts
- src/scanner/scan.ts
- test/fixtures/app_koa_with_ts/src/config/plugin.default.ts
- test/fixtures/app_koa_with_ts/src/config/plugin.dev.ts
- test/fixtures/app_koa_with_ts/src/test_duplicate_plugin/meta.yaml
- test/scanner.test.ts
- Plugin 抽象 getPath 能力、增加 path/package 互斥判断
- Config 相关 Loader 重构，支持对 PluginConfig 进行预处理
- Scanner 局部逻辑重构
- 重构 getAllConfig 兼容上述插件处理逻辑
- 修正多环境条件下的配置数据隔离 BUG
- 从 Manifest 中移除 PluginConfig，防止运行时对其的重新合并诱发两阶段配置状态不一致
- 增加相关单元测试用例
resolve #109
> refactor: 支持 Plugin.package 字段在扫描阶段的预处理

- src/scanner/scan.ts
最早的 Scanner 实现中遍历目录是倒序进行，因此拿到的排序后的 plugin 列表也需要 `reverse` 后遍历。
新版的 Scanner 已经是顺序扫描 framework -> plugin -> app 目录，这里的 `reverse` 会造成插件依赖顺序颠倒，此 PR 旨在修复此 BUG
> fix: sorted plugin list should not be reversed

- package.json
- src/plugin/types.ts
- src/scanner/scan.ts
- src/scanner/types.ts
- src/scanner/utils.ts
- test/fixtures/app_koa_with_ts/src/redis_plugin/meta.yaml
- test/fixtures/app_koa_with_ts/src/redis_plugin/not_to_be_scanned_dir/not_to_be_scanned_file.ts
- test/fixtures/app_koa_with_ts/src/redis_plugin/not_to_be_scanned_file.ts
- test/scanner.test.ts
related #129 
改动点如下：
- BREAKING! Scanner 中所有 `excluded` 均调整为 `exclude`
- `Scanner.formatWalkOptions` 补充逻辑： `exclude` 使用默认常量序列 + 插件 Meta 中声明的 exclude 值（未声明为空）
对于 #129 实现中的其他部分：
- extensions 目前看不涉及单独配置，暂不考虑支持
- Framework 中目前未包括对 Metadata 的处理（不要求 meta.yaml），此处需要评估是否有必要增加，或在其他位置声明 exclude/configDir（如 package.json）cc @hyj1991 
cc @hyj1991  @JerrysShan @wengeezhang
> refactor(scanner): modify exclude option for plugin & excluded rename

- src/application.ts
- src/trigger/index.ts
- src/types.ts
- test/fixtures/artus_application/src/controller/plugin.ts
- test/fixtures/artus_application/src/index.ts
- test/fixtures/artus_application/src/plugins/artus_plugin_mysql_ob/src/app.ts
- test/fixtures/artus_application/src/plugins/artus_plugin_mysql_rds/src/app.ts
- test/fixtures/artus_application/src/plugins/artus_plugin_redis/src/app.ts
- test/loader.test.ts
- test/logger.test.ts
> refactor: remove getContainer

- src/loader/impl/config.ts
- src/loader/impl/framework_config.ts
- src/loader/impl/plugin_config.ts
- src/loader/utils/config_file_meta.ts
- src/scanner/scan.ts
- test/fixtures/app_koa_with_ts/src/config/config.dev.ts
- test/scanner.test.ts
resolve #154 
临时方案，暂时解决 BUG，后续需对 Scanner 进行重构，理清递归过程
> feat(scanner): filter config with env

- package.json
- src/constant.ts
- src/decorator.ts
- src/index.ts
- src/lifecycle/index.ts
- src/loader/impl/lifecycle.ts
- test/fixtures/app_koa_with_ts/src/app.ts
- test/fixtures/artus_application/src/controller/conifg.ts
- test/fixtures/artus_application/src/controller/hello.ts
- test/fixtures/artus_application/src/controller/plugin.ts
- test/fixtures/artus_application/src/plugins/artus_plugin_mysql_ob/src/app.ts
- test/fixtures/artus_application/src/plugins/artus_plugin_mysql_rds/src/app.ts
- test/fixtures/artus_application/src/plugins/artus_plugin_redis/src/app.ts
- test/fixtures/custom_instance/bootstrap.ts
- test/fixtures/frameworks/bar/src/http.ts
- test/fixtures/frameworks/bar/src/lifecycle.ts
- test/fixtures/frameworks/layer/foo/foo1/src/lifecycle.ts
- test/fixtures/frameworks/layer/foo/foo2/src/lifecycle.ts
- test/fixtures/trigger/event/app.ts
- test/fixtures/trigger/http/app.ts
- test/fixtures/trigger/timer/app.ts
- test/framework.test.ts
ref: https://github.com/artusjs/core/issues/143
> feat: support inject in lifecycle

- src/scanner/scan.ts
- src/scanner/types.ts
> fix(scanner): support config with function has app params

- package.json
pnpm version: 6.32.3
```
tsc -p ./tsconfig.build.json
src/exception/handler.ts:5:1 - error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.
5 @Injectable()
~~~~~~~~~~~~~
Found 1 error in src/exception/handler.ts:5
 ELIFECYCLE  Command failed with exit code 2.
```
> chore: pnpm 6.32.3 build failed

- src/lifecycle/index.ts
- test/lifecycle.test.ts
生命周期的 hooks 应该只执行一次。
> 举例：使用 ts-node 跑 artus 应用，ctrl + c 的时候，SIGINT 触发两次会触发两次 `beforeClose`
> fix: lifecycle hook should trigger only one time

- src/loader/impl/module.ts
> refactor(loader): set default scope EXECUTION in module loader

- src/lifecycle/index.ts
- src/loader/factory.ts
- src/loader/impl/lifecycle.ts
- src/loader/impl/module.ts
- src/loader/impl/plugin_config.ts
- src/loader/types.ts
- src/scanner/scan.ts
- src/scanner/utils.ts
- test/fixtures/app_with_lifecycle/bootstrap_duplicated.ts
- test/fixtures/app_with_lifecycle/bootstrap_load.ts
- test/fixtures/app_with_lifecycle/bootstrap_ready.ts
- test/fixtures/module_with_custom_loader/src/index.ts
> fix(loader): lifecycle loader support named export

- package.json
`@artus/eslint-config-artus` 依赖的 `@typescript-eslint/typescript-estree` 最新版本 5.35.1 无法支持最新的 `typescript@4.8.2`：
```bash
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.8.0
YOUR TYPESCRIPT VERSION: 4.8.2
Please only submit bug reports when using the officially supported version.
=============
```
导致 lint 报错，并使得 CI 全部挂掉：https://github.com/artusjs/core/actions/runs/2930918347
考虑临时通过 sermver 锁定到 4.7.x 来解决，观察后续的依赖更新状态再解锁。
typescript 的版本并不会遵循 sermver 规则，minor & patch 版本的更新产生的 break 需要在 spec 中约定一个明确的处理方式，并透出给用户。
> fix: lint error

- src/scanner/scan.ts
- test/fixtures/frameworks/bar/src/lifecycle.ts
- test/specific.test.ts
此 PR 旨在调整 Scanner 扫描文件阶段，用户配置的 framework 属性优先于 Scanner 传入的 framework 配置
Reference: close #187
> feat: the user-configured framework is preferred

- src/loader/types.ts
- src/scanner/scan.ts
- test/scanner.test.ts
本 PR 向 Manifest 类型定义和 Scanner.scan 方法逻辑中增加了 `pluginConfig` 字段，值为经解析后的插件配置，用于：
- 运行时数据上报 / 构建时依赖分析
- 多 Env 场景下的运行时 Manifest 合并逻辑中，作为 plugin 启用判断的辅助数据
> feat(scanner): add parsed pluginConfig to manifest

- src/exception/impl.ts
标准错误实现中将消息格式化时间提前到构造时，原因是 console 打印日志时读不到 getter
> fix(exception): format error message when constructed

- src/plugin/impl.ts
- src/scanner/scan.ts
- src/utils/fs.ts
- test/scanner.test.ts
> fix: compatible for no config

- src/constant.ts
- test/fixtures/app_with_lifecycle/test/throw.ts
- test/scanner.test.ts
将原来配置的 `test/` 改成 `test`，因为匹配的都是文件夹名和文件名，有 `/` 会导致匹配不到 test 目录。
> fix: correct test dir

- src/plugin/factory.ts
related #229 
1.0.4 版本可能造成使用预先生成的 manifest 文件时，因为缺少扫描器补入的 baseDir（对 package 字段意义不大）造成 require.resolve 失败
代码很早之前就在，之前未触发的主要原因是：
- Scanner 之前基于避免非必要合并的考虑，剔除了 `plugin-config` loader 的全部 item，所以确实 `loaderState.baseDir` 的 item 不会进入运行时的 loader
- 重构期间为了对齐所有 config 的合并逻辑，移除了剔除 item 的代码
> fix(plugin): prevent require.resolve paths arguments undefined

- package.json
```
Error: Cannot find module 'reflect-metadata'
Require stack:
/node_modules/.store/@artus+core@1.0.5/node_modules/@artus/core/lib/application.js
/node_modules/.store/@artus+core@1.0.5/node_modules/@artus/core/lib/index.js
/node_modules/.store/@artus-cli+artus-cli@0.2.3/node_modules/@artus-cli/artus-cli/dist/index.js
/node_modules/.store/egg-bin@6.1.2/node_modules/egg-bin/dist/bin/cli.js
```
> deps: add reflect-metadata to peerDependencies

- src/constant.ts
sanner exclude rule should no exclude `meta.(t/j)s`
> fix: should no exclude meta.js

- src/application.ts
- src/loader/factory.ts
- src/loader/helper.ts
- src/loader/index.ts
- src/loader/types.ts
- src/plugin/impl.ts
- src/plugin/types.ts
- src/scanner/task.ts
- src/scanner/types.ts
- src/scanner/utils.ts
- src/types.ts
- test/__snapshots__/scanner.test.ts.snap
- test/loader.test.ts
- test/utils/index.ts
- 抽离 LoaderFactory 的 find 能力，方便后续做 auto 的解构
- 重构 LoaderFactory.loadManifest 支持 Manifest V2
- 调整 Plugin 支持 Ref 模型
- 优化类型和边缘逻辑
- 调整单测确保 Loader 单测通
related #241
> refactor: support load manifest version 2

- src/configuration/index.ts
- src/scanner/task.ts
- src/scanner/utils.ts
`scanner/utils` 中的 `loadConfigItemList` 方法用于在扫描每个 Ref 时加载其内部的配置，为了保证函数类型配置工作正常，此前复用了 `app`，但此前仅在扫描任务完全结束时清理了一次 ConfigStore，所以可能在某些 ref 中拿到被不正常合并后的配置，造成加载异常。
本 PR 调整项包括：
- `loadConfigItemList` 调整实现
- 通过在 async 过程中替换 configStore 指向，确保每次调用该方法时使用一干净的 Store，调用结束前还原
- 移除已无必要的清理逻辑，减少误解
- 移除已无调用的 `getAllConfig` 方法，减少误解
> fix(scanner): use individual store for loadConfigItemList

- src/exception/utils.ts
- test/exception_filter.test.ts
- test/fixtures/exception_filter/bootstrap.ts
- test/fixtures/exception_filter/error.ts
- test/fixtures/exception_filter/filter.ts
- test/fixtures/exception_filter/service.ts
之前考虑通过 instanceof 匹配错误类的话，需要对 Filter 全量 Map 做遍历，有性能损耗，所以匹配时直接用了 `Map().has(constructor)` 的方案；
但这种情况下，对于以下的继承场景将有遗漏，如下：
```ts
class BaseError extends Error {}
class InputError extends BaseError {}
@Catch(BaseError)
class SomeFilter implements ExceptionFilterType {
catch(err) {
// 这里是拦截不到 InputError 的
}
}
```
所以计划匹配阶段增加对异常实例原型链的循环，从子到父，直到 prototype 不为 class（根级），期间如有命中直接返回（相当于越精确的 Filter 优先级越高，如上例 `@Catch(InputError)` > `@Catch(BaseError)`）；
以此策略支持有继承场景的 ExceptionFilter，考虑到异常的继承嵌套不会很长（通常比 Filter 数量小且可控），性能损失相对有限。
> refactor(exception): exception filter need to handle inheritance of error clazz

- src/plugin/factory.ts
- src/plugin/impl.ts
- src/plugin/types.ts
- test/__snapshots__/scanner.test.ts.snap
- test/fixtures/plugins/plugin_d/meta.json
- test/plugin.test.ts
此前的设计中，因为拓扑排序阶段的所有节点（边的端点）都需要有效且存在，所以 optional 依赖（可能不存在）会在边列表中全部排除，不参与顺序计算；
但即便是 optional 的依赖，也可能排在当前插件后面，不进行顺序计算将带来非预期行为（如奇怪的容器内元素不存在报错，插件开了，因为顺序不对拿不到）；
所以在依赖检查环节补充本 MR 的逻辑，对于已开启并存在的 optional 依赖，也要参与边生成/算序环节
> fix(plugin): optional plugin also need to calc order

- src/plugin/common.ts
pnpm 可能出现依赖打平（flat）在 `node_modules/.pnpm/node_modules`；
这种场景下，只使用扫描的 baseDir 加载包，可能找不到包路径
> fix(plugin): add artus dir to package path resolver for pnpm

- package.json
- src/plugin/common.ts
- src/plugin/factory.ts
- src/plugin/impl.ts
- src/plugin/types.ts
- test/plugin.test.ts
之前插件的按依赖排序使用了拓扑排序算法；
- 优点是有向无环图理论复杂度低，可以较容易检查循环依赖；
- 缺点是不稳定排序，可能造成 config 内锚定的无关依赖顺序漂移；
而插件排序场景中对于不能靠 `dependencies` 声明来实现的，较普遍使用 pluginConfig 中的顺序做依赖顺序保障，而拓扑排序使顺序漂移问题变得不易发现和处理。
例如，当我们有这段配置时：
```js
[
{ name: 'a', deps: [ 'b', 'c' ] },
{ name: 'b', deps: [ 'c' ] },
{ name: 'c', deps: [] },
{ name: 'd', deps: [ 'c' ] }
]
```
依赖链路为：
```plain
a -> b -> c
a -> c
b -> c
d -> c
```
期待的顺序为 `c, b, a, d`，即对于 a / d 作为无关项保持配置中的顺序；
然而，因为拓扑排序不稳定，最终顺序与依赖链长度有关（indegree 出队顺序），所以结果会是 `c, b, d, a`，如果 a / d 间有相互影响，将产生不可用现象
综上，有必要对该部分做出改变
该 PR 通过 DFS 重新实现 `PluginFactory.createFromConfig` 方法，在递归过程中进行 `optional` 和循环依赖检查；
同时优化了 Plugin 类的实现代码，移除了无用方法;
调整了 plugin 相关单测，顺序保证增加到 4 个，并使用上述的依赖链 case 做验证
> refactor(plugin): use standard dfs instead of topological for stable sort

- src/application.ts
- src/lifecycle/index.ts
- test/lifecycle.test.ts
beforeClose 钩子通常用于进行业务逻辑的收尾处理，此时仍可能使用插件提供的 Client；
正向触发 hook 可能造成插件中的链接比应用更早被回收，不符合预期；
所以简单地针对这个钩子，在 emitHook 阶段反转 fnList
> fix: reverse emit function list when beforeClose hook

- .gitignore
- src/configuration/index.ts
- src/constant.ts
- src/loader/factory.ts
- src/loader/impl/config.ts
- src/loader/types.ts
- src/scanner/task.ts
- src/scanner/utils.ts
- test/__snapshots__/scanner.test.ts.snap
- test/config.test.ts
- test/fixtures/app_koa_with_ts/src/bootstrap.ts
- test/fixtures/app_with_config/bootstrap.ts
- test/fixtures/exception_filter/bootstrap.ts
- test/fixtures/exception_invalid_filter/bootstrap.ts
- test/fixtures/exception_with_ts_yaml/bootstrap.ts
- test/fixtures/logger/src/index.ts
- test/fixtures/module_with_custom_loader/src/index.ts
- test/fixtures/module_with_ts/src/index.ts
- test/utils/index.ts
之前在 Scan 阶段预处理的 pluginConfig，存在边界 case：
- 插件合集 a 内 default 启用了插件 b
- app 在 prod 环境未启用插件合集 a
- 但预处理过程中把全部 default 合并，全部 prod 合并
- 预期应为 prod 是 a 禁用，所以不涉及 b 的工作
- 但实际出现总和 default 中 b 启用，prod 中 a 禁用，合并结果中 b 仍被启用
本 PR 调整了 Scanner & Loader 的插件配置部分逻辑：
- 将 pluginConfig 字段分拆到 refMap 和 extraPluginConfig（扫描时指定的）；
- load 阶段以 ref（插件/应用）为单位，每层按环境合并插件配置；
- 用上面按环境合并的配置排序、加载 itemList
> fix: merge plugin config when load because of plugin preset
